// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvyzDiDf7bNMAwUTrajcm5J2KJkSQsNw',
    appId: '1:224145657542:web:ecc4ec7d20e4f59c7bd1c7',
    messagingSenderId: '224145657542',
    projectId: 'flutter-wallet-app-4e023',
    authDomain: 'flutter-wallet-app-4e023.firebaseapp.com',
    databaseURL: 'https://flutter-wallet-app-4e023-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-wallet-app-4e023.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWtLwzNY41DVlr4_pC60k9hk4vsstX0E',
    appId: '1:224145657542:android:d250665768596f627bd1c7',
    messagingSenderId: '224145657542',
    projectId: 'flutter-wallet-app-4e023',
    databaseURL: 'https://flutter-wallet-app-4e023-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-wallet-app-4e023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyXNhBbItAqL-uVVVVunmxKQGLf9CPmA',
    appId: '1:224145657542:ios:cddd603b543f2b777bd1c7',
    messagingSenderId: '224145657542',
    projectId: 'flutter-wallet-app-4e023',
    databaseURL: 'https://flutter-wallet-app-4e023-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-wallet-app-4e023.firebasestorage.app',
    iosBundleId: 'com.example.walletApp4e023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyXNhBbItAqL-uVVVVunmxKQGLf9CPmA',
    appId: '1:224145657542:ios:a2a014c50a0ccf167bd1c7',
    messagingSenderId: '224145657542',
    projectId: 'flutter-wallet-app-4e023',
    databaseURL: 'https://flutter-wallet-app-4e023-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-wallet-app-4e023.firebasestorage.app',
    iosBundleId: 'com.example.walletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwvyzDiDf7bNMAwUTrajcm5J2KJkSQsNw',
    appId: '1:224145657542:web:f564f6e220d4e77a7bd1c7',
    messagingSenderId: '224145657542',
    projectId: 'flutter-wallet-app-4e023',
    authDomain: 'flutter-wallet-app-4e023.firebaseapp.com',
    databaseURL: 'https://flutter-wallet-app-4e023-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-wallet-app-4e023.firebasestorage.app',
  );
}
